### ISSUE TITLE
Online API service

### ISSUE THREAD

**Issue by astrawin** [Kibo/AstroAPI#3]
Hi Kibo,

I landed here through first https://astrologyapi.docs.apiary.io/#reference/0/cusps/cusps
then on from https://gitmemory.com/Kibo

I am using AstroChart javascript code to produce charts based on time and geolocation.

I was looking for a javascript library or an API to get the planets/cusps data to feed in the chart.

Is there an online web service i can use to get the ephemeris data for the AstroChart, currently i can't host a jboss or java endpoint service as i am basing my project on shared hosting environment.

I would appreciate any help.

Thanks,
Alex.

**Comment by Kibo** [comment]
Hi Alex

1)
once upon a time I have seen the implementation of JS ephemeris here on Github. I do not know what accuracy is it and I do not know whether the project is still alive.

2)
They say some men are going to launch a public astrology server. Sorry I dont know details.

3)
For testing, you can use: http://s.kibo.cz:8080

Tom
